language: Swift
osx_image: xcode11.3
xcode_project: TLCommon.xcodeproj
script: xcodebuild -project TLCommon.xcodeproj -scheme "TLCommon" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=latest'

